### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated.

### ISSUE THREAD

**Issue by chengchingwen** [allenai/ARC-Solvers#20]
I try to run the BiLSTM Max-out trained model but I get the following error message
```
Traceback (most recent call last):
  File "arc_solvers/run.py", line 10, in <module>
    from arc_solvers.commands import main  # pylint: disable=wrong-import-position
  File "/home/peter/peter/clone/ARC-Solvers/arc_solvers/commands/__init__.py", line 1, in <module>
    from allennlp.commands import main as main_allennlp
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 4,
 in <module>
    from allennlp.commands.serve import Serve
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/commands/serve.py", line 28, i
n <module>
    from allennlp.service import server_sanic
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/service/server_sanic.py", line
 20, in <module>
    from allennlp.models.archival import load_archive
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/models/__init__.py", line 7, i
n <module>
    from allennlp.models.crf_tagger import CrfTagger
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/models/crf_tagger.py", line 10
, in <module>
    from allennlp.modules import Seq2SeqEncoder, TimeDistributed, TextFieldEmbedder, ConditionalRandomField
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/modules/__init__.py", line 13,
 in <module>
    from allennlp.modules.seq2seq_encoders import Seq2SeqEncoder
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/modules/seq2seq_encoders/__ini
t__.py", line 83, in <module>
    from allennlp.modules.alternating_highway_lstm import AlternatingHighwayLSTM
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/modules/alternating_highway_ls
tm.py", line 10, in <module>
    from allennlp.custom_extensions._ext import highway_lstm_layer
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/allennlp/custom_extensions/_ext/highway
_lstm_layer/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/peter/peter/clone/ARC-Solvers/arc/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, i
n <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```
which says that `torch.utils.ffi` is deprecated.

**Comment by aghie** [comment]
I recently had this problem too. Downgrading to pytorch 0.3.1 worked for me. I was using pytorch 1.0.0, and it seems to be a problem coming from pytorch: https://github.com/pytorch/pytorch/issues/15645
